<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '公司简介',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507105004772.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'intro',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list1","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsijianjie',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '我要存房',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507024530936.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'cunfang',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list2","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'woyaocunfang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '我要出租',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507024726451.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'rent',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list3","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'woyaochuzu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '我要求租',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507025455403.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'qiuzu',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list4","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'woyaoqiuzu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '人才招聘',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507025605667.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'join',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list5","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'rencaizhaopin',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => '联系我们',
    'style' => '',
    'image' => 'http://localhost/yijiawuye/uploadfile/2017/0507/20170507025704429.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'contact',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"","list_template":"list6","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'lianxiwomen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => '轮播图',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'wheel',
    'url' => 'http://localhost/yijiawuye/index.php?m=content&c=index&a=lists&catid=15',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '15',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'lunbotu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>